
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdohist.h"

/*
* The configuration table for devices
*/

XDohist_Config XDohist_ConfigTable[] =
{
	{
		XPAR_DOHIST_0_DEVICE_ID,
		XPAR_DOHIST_0_S_AXI_CRTL_BUS_BASEADDR
	}
};


