// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern void doGain ( hls::stream< ap_axis< 32 ,2 ,5 ,6 > > & inStream,  hls::stream< ap_axis< 32 ,2 ,5 ,6 > > & outStream,  int gain);

