# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths A:/FYP/HLSTutorials/axisStreamProject/solution1 [current_fileset]

add_files A:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/ipshared/xilinx.com/doGain_v1_0/07f27a6a/constraints/doGain_ooc.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all a:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all A:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files A:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib A:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir A:/FYP/HLSTutorials/project_axis_stream/project_axis_stream.cache/wt [current_project]
set_property parent.project_dir A:/FYP/HLSTutorials/project_axis_stream [current_project]
catch { write_hwdef -file design_1_wrapper.hwdef }
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint design_1_wrapper.dcp
report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb
