// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdohist.h"

extern XDohist_Config XDohist_ConfigTable[];

XDohist_Config *XDohist_LookupConfig(u16 DeviceId) {
	XDohist_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDOHIST_NUM_INSTANCES; Index++) {
		if (XDohist_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDohist_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDohist_Initialize(XDohist *InstancePtr, u16 DeviceId) {
	XDohist_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDohist_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDohist_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

