// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern void doHistStretch ( hls::stream< ap_axiu< 8 ,2 ,5 ,6 > > & inStream,  hls::stream< ap_axiu< 8 ,2 ,5 ,6 > > & outStream,  unsigned char xMin,  unsigned char xMax);

